### PR TITLE
Resource Release Page

### PR DESCRIPTION
**Pull request by superdav42**
# Describe what your pull request addresses
For https://github.com/unfoldingWord/gateway-admin/issues/128

Most things should be addressed from the Epic.

## Left to do:
- Use correct OBS resources when OBS is selected
- Better error condition handling
- Artifacts such as PDFs that are currently attached to releases will not be attached. 
- A few TODO are in the code related to updating the versions of related resources in manifest.yml
- Some code cleanup could help.

## Caveats:
- I don't have access to commit to master so some steps fail

## Test Instructions

- `yarn dev`
- visit http://localhost:3000/releaseRepo?server=QA
- Select all books  and all resources
- Enter something in name and notes
- Click release
- Check log and network tab of chrome dev tools.
- Repeat to ensure newer versions numbers are used

### CODE REVIEW

**Comment by mandolyte** [comment]
For https://qa.door43.org/Es-419_gl/es-419_tn/branches
I deleted all the branches created in testing 

For https://qa.door43.org/Es-419_gl/es-419_tn/releases
I deleted all the releases created in testing

Logged in to https://deploy-preview-132--gateway-admin.netlify.app/

**Test 1**
Release just Titus TN with no prior releases and see what happens.
*Results:* release cut from the master branch
*Cleanup:* delete new release and the "release_v65" branch 

**Test 2**
Create a branch "release_v0" with only Genesis and Ruth.
- refresh and re-login
- released titus tn
*Results:* It created v65 (not v1) and again all content from master was present

**Test 3**
Use the v65 commit and trim it to just Genesis and Ruth.
**Results:** Not allowed... must be on a branch to delete files.

**Test 4**
Use the branch "release_v65" and trim it.
*Results:*
- refreshed page and logged in
- created v66, but Titus was not in it.

**Comment by mandolyte** [comment]
**Setup**

- using local code, not netlify preview
- deleted all testing branches and releases

**Test 1**
Release Titus TN only with no prior release branch present.
*Results:*
- v65 release created; contains all content from master
- branch "release_v65" was created

**Test 2**
Update release_v65 branch to only contain GEN and RUT and release again.
*Results:*
- first, restarted app
- release v66 was created; only had v65 files; Titus is missing

**Test 3**
Just trying again...
*Results:*
- v67 release created; Titus is still missing.

**Conclusion**
1. Appears that files selected by user are not being added to the release branch from the master branch.
2. The manifest is not being updated either. After several releases it remains unchanged.

See https://qa.door43.org/Es-419_gl/es-419_tn/releases

**Comment by superdav42** [comment]
Can you share what you see in Chrome Dev tools Network tab? You should see it trying to fetch and add Titus file but obviously it didn't work and the network tab will give us a clue why.

**Comment by superdav42** [comment]
Update it so we can release OBS resources and OBS itself too.

**Comment by mandolyte** [comment]
- Org es-419_gl
- Lang es-419
- TN
- Ruth

**Test 1**
Two prior releases done manually; none by this tool. Latest is v65.
The manifest has some odd things in it. Will remove the two bad entries (see below) before running test. After correction, the manifest has Genesis, Ruth, and Titus.

1. In gA, select above as starting point, then go to release page.
2. *Notice that wording has reverted to book package language* - the text changes I made earlier are lost (again).
3. *Question about the warning about being a first release*... how is this determined? What if one out of the 9 resources had been published what would it say?
4. Selected Ruth and TN, prod release, and added some text for name and notes.
5. After clicking to release the TN for Ruth, this message appears "tn Result Created release v66 of es-419_tnView v66 release"
6. Results:
- a third new release shows
- name and notes look good.
- version is v66 - good.
- the manifest looks good with updated dates and version
- however, all the files from master are present. That isn't correct. Should only have three (Gen, Rut, and Tit).


```yaml
projects:
  - title: Genesis
    versification: ''
    identifier: gen
    sort: 1
    path: ./en_tn_01-GEN.tsv
    categories:
      - bible-ot
  - title: Ruth
    versification: ''
    identifier: rut
    sort: 8
    path: ./en_tn_08-RUT.tsv
    categories:
      - bible-ot
  - &ref_0
    title: Zechariah
    versification: ufw
    identifier: zec
    sort: 38
    path: ./es-419_tn_38-ZEC.tsv
    categories:
      - bible-ot
  - *ref_0
  - title: Tito
    versification: ''
    identifier: tit
    sort: 56
    path: ./es-419_tn_57-TIT.tsv
    categories:
      - bible-nt
```

**Comment by superdav42** [comment]
> however, all the files from master are present. That isn't correct. Should only have three (Gen, Rut, and Tit).

This is because it's not going based on what is in the manifest just what is selected on the first release. The extra files are `en` which I think shouldn't be there at all. The code just deletes to files based on what it expects their names to based on the resource and language code. Any extra files will just be left alone.

I think this is ready for more testing. I fixed the problems we noticed this morning which were nothing wrong with the code just bad previous releases. 

Perhaps we should merge this then let @elsylambert test.

**Comment by mandolyte** [comment]
Org: es-419_gl
lang: es-419
resource: tn

**Setup:**
1. removed all releases except the one done by user
2. removed all "release" branches
3. corrected manifest to just have gen, rut, and titus

**Test 1**
Try to release just Titus, but with GEN and RUT in the manifest as well.

Results:
1. The "Book Package" language is still there.
1. master branch manifest updated with version and dates. The Projects section looks good
2. ERROR: the "release_v65" branch created, but it contains all the files from master, not just the one selected or the ones in the manifest.
2. release v65 created with name and notes provided
3. ERROR: all files in master branch are present, not just the one selected or just the ones in the manifest.
4. The v65 manifest contains gen, rut, and tit. So that's probably ok.

**Comment by mandolyte** [comment]
Org: es-419_gl
Repo: es-419_tn

**Setup**
- Deleted the test release v65 (leaving original v64.1) and removed the release branch release_v65
- Deleted browser local storage (there may be some "conflict" between gA and gT give that at present they both use "books")
- Manifest has three books: Gen, Rut, and Tit.
- Master branch has a bunch of other books in addition to the above three.

*Boilerplate*
First release
Releasing only **Titus**; other books waiting for review

**Test 1**
Release only Titus

*Results*
- only tn_TIT.tsv in release branch and in the release commit
- noticed that manifest in master branch was not updated. Perhaps because it didn't "change"??



**Test 2**
Let's try *both* Gen and Rut.

*Results*
- v66 released; looks good


**Recommend**
- Don't change filenames. Expect that the manifest is correct for files being released and fail if not (if file not where manifest says it is). 
- Remove all files from the **released** manifest that are not being released (first use only). After first time, the released manifest will be the "standard". The manifest in the master branch only needs to have the correct filename for the files being released.
- How about moving the status message so that it is between the bottom of the form and the two buttons at the bottom. That way the status and progress will not be missed. At least on my screens it is below the buttons and cannot be seen unless I happen to scroll up. This will push the buttons down, but that's ok. Thoughts?

**Comment by superdav42** [comment]
> How about moving the status message so that it is between the bottom of the form and the two buttons at the bottom. That way the status and progress will not be missed. At least on my screens it is below the buttons and cannot be seen unless I happen to scroll up. This will push the buttons down, but that's ok. Thoughts?

Done


> Don't change filenames. Expect that the manifest is correct for files being released and fail if not (if file not where manifest says it is).
> Remove all files from the released manifest that are not being released (first use only). After first time, the released manifest will be the "standard". The manifest in the master branch only needs to have the correct filename for the files being released.

Good idea. I updated the code to check for path from manifest file. It will throw an error and stop a release if a selected file is not found in the manifest file. There is a small problem with removing all the files from the manifest on the first release. As it is releasing only Titus first then selecting Ruth in the next release will complain of a missing file since the Ruth project was removed from the manifest in the first release and it's in a non-standard path. We could leave it as is and expect the admin to manually update the manifest file or rename the file OR we could update the functions manifestAddBook and getProject() to look in the non-standard paths and use them if they exist. Either way we could start beta testing as is. I think it's in a good place and should alert the user of any errors that happen.

**Pull request merged**
