### PR TITLE
Feature cn 11 add cypress tests

### PR DESCRIPTION
**Pull request by mandolyte**
# Describe what your pull request addresses

- [ ] Setup cypress with a single test to login and select organization and language against QA DCS

## Test Instructions

- [ ] In `TESTING.md`, follow the steps in the section "Cypress Tests"

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
One suggestion would be to add  `cypress/videos/` to git ignore.  Don't need to be committing large test results.

**Comment by PhotoNomad0** [comment]
You might also consider adding it to github actions so the tests run automatically when you push to github.  An example in how to do it is in GWE - look for the yaml file in .github folder.

**Comment by mandolyte** [comment]
I think I'll wait before adding cypress to run on the server. Perhaps when I have more serious tests written.

**Review by PhotoNomad0 — APPROVED** [review]
LFTM

**Pull request merged**
